# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(567, 510)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 541, 481))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.447, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton:hover{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.447, stop:0 rgba(20, 131, 120, 219), stop:1 rgba(23, 56, 102, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"/*\n"
"Padding-left:5px;\n"
"padding-top:5px;\n"
"*/\n"
"\n"
"background-color:qlineargradient(spread:reflect, x1:0.122, y1:0.222045, x2:0.888, y2:0.222, stop:0.162362 rgba(19, 52, 97, 251), stop:0.5 rgba(83, 142, 190, 255), stop:0.913284 rgba(23, 56, 102, 255));\n"
" border: 2px solid rgb(0,0,0,0); /* Establece el color del borde gris plomo */\n"
"font: 50 11pt \"Bahnschrift SemiCondensed\";\n"
"}\n"
"\n"
"\n"
"\n"
"/*SEGUNDA PARA BOTONES REDES SOCIALES*/\n"
"QPushButton#pushButton_2{\n"
"background-color:rgba(0,0,0,0);\n"
"color:rgba(85,98,112,255);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_2:hover{\n"
"\n"
"color:rgba(131,96,53,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_2:pressed{\n"
"\n"
"Padding-left:2px;\n"
"padding-top:2px;\n"
"color:rgba(91,88,53,255);\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 450))
        self.label.setStyleSheet("border-image: url(:/images/FondoRPA.png);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(250, 60, 271, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel#label_4{\n"
"/*\n"
"color: rgb(0, 0, 0,200);*/\n"
"color: rgba(20, 131, 120, 219);\n"
"}\n"
"\n"
"\n"
"QLabel#label_4:hover{\n"
"/*\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.447, stop:0 rgba(20, 131, 120, 219), stop:1 rgba(23, 56, 102, 255));*/\n"
"color: rgba(23, 56, 102, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 251, 450))
        self.label_2.setStyleSheet("\n"
"background-color: rgb(50,100,50,50);\n"
"border-top-left-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(310, 280, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(260, 410, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(9)
        font.setKerning(False)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("\n"
"\n"
"QLabel#label_5{\n"
"\n"
"color: rgba(20, 131, 120, 219);\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel#label_5:hover{\n"
"/*\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.447, stop:0 rgba(20, 131, 120, 219), stop:1 rgba(23, 56, 102, 255));*/\n"
"color: rgba(23, 56, 102, 255);\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 251, 450))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 210, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 361, 171, 41))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BotRPA_00001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 119, 251, 231))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: rgb(0,0,0,60);\n"
"color: rgb(255,255,255,210);\n"
"padding-top: 15px;\n"
"padding-left: 30px; /* Crea un margen de 10 píxeles a la izquierda */")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"\n"
"QLabel {\n"
"\n"
"color: rgb(255,255,255,210);\n"
"\n"
"padding-left: 10px; /* Crea un margen de 10 píxeles a la izquierda */\n"
"}")
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 10, 31, 31))
        self.pushButton_3.setStyleSheet("\n"
"\n"
"/*SEGUNDA PARA BOTONES REDES SOCIALES*/\n"
"QPushButton#pushButton_3{\n"
"background-color:rgba(0,0,0,0);\n"
"color:rgba(85,98,112,255);\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton#pushButton_3:hover{\n"
" icon: none;\n"
"\n"
"/*\n"
"    background-image: url(:/images/cerrar_1.png);\n"
" image-size: 100px 100px; /* Ajusta el tamaño según tus necesidades */\n"
"\n"
"\n"
"    /* Establece la imagen normal como icono */\n"
"    icon: url(\":/images/cerrar_1.png\");\n"
"    icon-size: 10px 10px; /* Ajusta el tamaño según tus necesidades */\n"
"Padding-left:1px;\n"
"padding-top:1px;\n"
"color:rgba(91,88,53,255);\n"
"\n"
"\n"
"}\n"
"")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(270, 160, 31, 21))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/images/user.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(270, 220, 31, 21))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/images/passwdr.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(260, 420, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"\n"
"\n"
"QLabel#label_10{\n"
"/*\n"
"color: rgb(0, 0, 0,200);*/\n"
"color: rgba(20, 131, 120, 219);\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel#label_10:hover{\n"
"/*\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.447, stop:0 rgba(20, 131, 120, 219), stop:1 rgba(23, 56, 102, 255));*/\n"
"color: rgba(23, 56, 102, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_10.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "ENDIRECTO"))
        self.lineEdit.setPlaceholderText(_translate("Form", "User Name"))
        self.pushButton.setText(_translate("Form", "LOGIN"))
        self.label_5.setText(_translate("Form", "        ©2023 EQUIPO RPA"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton_2.setToolTip(_translate("Form", "Desarrollador:  Jonathan Vera Segura"))
        self.label_6.setText(_translate("Form", "Sistema RPA\'s"))
        self.label_7.setText(_translate("Form", "                       Hola \n"
" solo podran acceder usuarios del \n"
" equipo de desarrollo y autorizados.\n"
" \n"
" Contacto: 945430381 \n"
" Correo:jveras@atento.com.pe   "))
        self.label_10.setText(_translate("Form", "      Atento, Lima PERÚ"))
import res_rc
